site_name: Modular Dashboard
site_description: 一个现代化的模块化仪表盘系统
site_url: https://wayneXuCN.github.io/ModularDashboard/
repo_url: https://github.com/WayneXuCN/ModularDashboard
repo_name: ModularDashboard
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.prune
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到暗色模式
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 切换到亮色模式
      primary: indigo
      accent: indigo
  
nav:
  - 首页: index.md
  - 项目概述: overview.md
  - 快速开始: getting-started.md
  - 用户指南:
      - user-guide/index.md
      - 安装指南: user-guide/installation.md
      - 配置管理: user-guide/configuration.md
      - 布局配置: user-guide/layout.md
      - 模块使用: user-guide/modules.md
  - 开发者指南:
      - developer-guide/index.md
      - 架构设计: developer-guide/architecture.md
      - 模块开发: developer-guide/module-development.md
      - 项目结构: developer-guide/project-structure.md
      - 贡献指南: developer-guide/contributing.md
  - API 参考:
      - api-reference/index.md
      - 模块基类: api-reference/module-base.md
      - 配置 API: api-reference/configuration.md
      - 存储 API: api-reference/storage.md
  - 内置模块:
      - modules/index.md
      - ArXiv 模块: modules/arxiv.md
      - GitHub 模块: modules/github.md
      - RSS 模块: modules/rss.md
      - 天气模块: modules/weather.md
      - 待办事项: modules/todo.md
  - 附录:
      - appendix/index.md
      - 故障排除: appendix/troubleshooting.md
      - 更新日志: appendix/changelog.md
      - 术语表: appendix/glossary.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: iso_date
      timezone: Asia/Shanghai
      locale: zh
      fallback_to_build_date: true
