site_name: Modular Dashboard Documentation
site_url: https://your-username.github.io/modular-dashboard/
repo_url: https://github.com/WayneXuCN/ModularDashboard
repo_name: modular-dashboard
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: indigo
  custom_dir: docs/theme

nav:
  - Home: README.md
  - Overview: overview.md
  - User Guide:
      - Installation: user-guide/installation.md
      - Getting Started: user-guide/getting-started.md
      - Configuration: user-guide/configuration.md
      - Layout: user-guide/layout.md
      - Packaging: user-guide/packaging.md
  - Modules:
      - Overview: modules/index.md
      - ArXiv: modules/arxiv.md
      - GitHub: modules/github.md
      - RSS: modules/rss.md
  - API Reference:
      - Overview: api/index.md
      - Module Base: api/module-base.md
      - Configuration: api/configuration.md
  - Development:
      - Overview: development/index.md
      - Project Structure: development/structure.md
      - Contributing: development/contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true
          site_name: Modular Dashboard Documentation
          nav_translations:
            Home: Home
            Overview: Overview
            User Guide: User Guide
            Installation: Installation
            Getting Started: Getting Started
            Configuration: Configuration
            Layout: Layout
            Packaging: Packaging
            Modules: Modules
            API Reference: API Reference
            Development: Development
            Project Structure: Project Structure
            Contributing: Contributing
